{% set name = "cdtime" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdat/cdtime/archive/v{{ version }}.tar.gz
  sha256: e6aa613bb509a67f8dc0050d68ffc86c33099e19cfb2b64374b53131b9646e52

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

  host:
    - python  {{ python }}
    - setuptools
    - libcdms
    - numpy
    - cdat_info >=8.1.1
    - libdrs_f

  run:
    - python  {{ python }}
    - setuptools
    - libcdms
    - cdat_info >=8.1.1
    - libdrs_f
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cdtime

about:
    home:  http://gitub.com/CDAT/cdtime
    license: '3-Clause BSD'
    license_file: 'bsd-3-clause.txt'
    summary: 'Climate calendar manipulation tools'
    description: |
        The cdtime module contains functions for converting between
        these forms, based on the common calendars used in climate
        simulation. Basic arithmetic and comparison operators are also available.


extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
