{% set name = "cdtime" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cdat/cdtime/archive/v{{ version }}.tar.gz
  sha256: 2e8e4df97762fd167e028aa9afcb588f90cb9c8c90e299da439c1277bd96d723

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}

  host:
    - python
    - setuptools
    - libcdms
    - numpy
    - cdat_info
    - libdrs_f

  run:
    - python
    - setuptools
    - libcdms
    - cdat_info
    - libdrs_f
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cdtime

about:
  home:  http://gitub.com/CDAT/cdtime
  license: '3-Clause BSD'
  license_file: 'bsd-3-clause.txt'
  summary: 'Climate calendar manipulation tools'
  description: |
      The cdtime module contains functions for converting between
      these forms, based on the common calendars used in climate
      simulation. Basic arithmetic and comparison operators are also available.
  dev_url: https://github.com/CDAT/cdtime

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
