{% set name = "cdtime" %}
{% set version = "2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UV-CDAT/cdtime/archive/v2.12.tar.gz
  sha256: 77f9c48ca411d17c31ea64e0b78cfe23fc137d88d10daf9fef987e8afc981565

build:
  number: 2
  skip: True  # [win] 

requirements:
  build:
    - python
    - setuptools
    - libcdms
    - numpy x.x
    - cdat_info
    - libdrs_f
    - gcc
  run:
    - python
    - setuptools
    - libcdms
    - cdat_info
    - libdrs_f
    - numpy x.x

test:
  imports:
    - cdtime

about:
  home: http://uvcdat.llnl.gov/documentation/cdms/cdms_3.html
  license: 'CCLRC'
  license_file: 'LICENSE'
  summary: 'Climate calendar manipulation tools'
  description: |
      The cdtime module contains functions for converting between 
      these forms, based on the common calendars used in climate 
      simulation. Basic arithmetic and comparison operators are also available.
  dev_url: https://github.com/UV-CDAT/cdtime

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
