{% set version = "3.1.3" %}
{% set build = 3 %}

package:
  name: cdtime
  version: {{ version }}

source:
  url: https://github.com/cdat/cdtime/archive/v{{ version }}.tar.gz
  sha256: 121b9e855c3889d145bc9730d36403df6fd1b7677e99076556e763c3e53a59d5

build:
  number: {{ build }}
  skip: True  # [win]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `cdtime * mpi_mpich_*` for mpich
  # `cdtime * mpi_*` for any mpi
  # `cdtime * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - setuptools
    - cython
    - libcdms
    - libcdms * {{ mpi_prefix }}_*
    - numpy
    - libnetcdf
    - libnetcdf * {{ mpi_prefix }}_*
    - cdat_info
    - libdrs_f
    - libdrs_f * {{ mpi_prefix }}_*

  run:
    - python
    - setuptools
    - libcdms * {{ mpi_prefix }}_*
    - libnetcdf * {{ mpi_prefix }}_*
    - cdat_info
    - libdrs_f * {{ mpi_prefix }}_*
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - cdtime

about:
    home:  http://gitub.com/CDAT/cdtime
    license: BSD-3-Clause
    license_file: bsd-3-clause.txt
    summary: Climate calendar manipulation tools
    description: |
        The cdtime module contains functions for converting between
        these forms, based on the common calendars used in climate
        simulation. Basic arithmetic and comparison operators are also available.
extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
    - downiec
    - muryanto1
    - jasonb5
    - xylar
