# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "lfx9PXQnR+UvnQkB/zuCzebgMPoKXrF4wUJfrhItmQ/F/oSNNfGwVQ9DEisrY3KlHIjz8dAQheNJ3q2qsGtyKT02XtF8cEqtUCIr0UfqfgrXv4kwl59a6GU5iacmWBWeefyUudVfcezsDuNuAsGDRhX5CqLugBYdLqKpBtj6k+xbBcA18/4ehfJRCJPD0ybp7PY8oeYP6+0xMqMe50cGZvY+TFgKU3FjcJaputRr/K7WRLAR1uWu/stjvC/sXfcgcRvC1XzaH9uhGEXMjvU0KKJhtneTVP1yxjIsjpipllDMUTFslaabnw1TJjfoZ/dXEbHBnbQfH9ADjwgQiIJRxzVGo9/z7ALZjbqZeHePPs8FCTk+DhfSX9qTPhh6unImlBJSr7fLWyoBTd+kZmDenHnbykH8b/RAWxmKjfAi0dTh4EXJ/sGdGszl+oof4CK5yFNgiS7RqDfcRMHjCRBRABmjvVJXNXWoS0djlEwGavDuKBbLjpyXJTcTrPEPORsv7DWEYVZ/AK776E7aJKRZMdmNzOuXRGTSW1yd8XOvurChlwZJj47+cMdj0tJE4n4fFVenQdrpbf8kPwwmXpsWq5V4f0Zoh2AntXhmutSrK3VOdzYA/Qbxp//6S11lz7806W2BI8SYdIrKcnPH4hmgOV9Y/VCTBI+WusDTAPREGfQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
