travis:
  secure:
    BINSTAR_TOKEN: lfx9PXQnR+UvnQkB/zuCzebgMPoKXrF4wUJfrhItmQ/F/oSNNfGwVQ9DEisrY3KlHIjz8dAQheNJ3q2qsGtyKT02XtF8cEqtUCIr0UfqfgrXv4kwl59a6GU5iacmWBWeefyUudVfcezsDuNuAsGDRhX5CqLugBYdLqKpBtj6k+xbBcA18/4ehfJRCJPD0ybp7PY8oeYP6+0xMqMe50cGZvY+TFgKU3FjcJaputRr/K7WRLAR1uWu/stjvC/sXfcgcRvC1XzaH9uhGEXMjvU0KKJhtneTVP1yxjIsjpipllDMUTFslaabnw1TJjfoZ/dXEbHBnbQfH9ADjwgQiIJRxzVGo9/z7ALZjbqZeHePPs8FCTk+DhfSX9qTPhh6unImlBJSr7fLWyoBTd+kZmDenHnbykH8b/RAWxmKjfAi0dTh4EXJ/sGdGszl+oof4CK5yFNgiS7RqDfcRMHjCRBRABmjvVJXNXWoS0djlEwGavDuKBbLjpyXJTcTrPEPORsv7DWEYVZ/AK776E7aJKRZMdmNzOuXRGTSW1yd8XOvurChlwZJj47+cMdj0tJE4n4fFVenQdrpbf8kPwwmXpsWq5V4f0Zoh2AntXhmutSrK3VOdzYA/Qbxp//6S11lz7806W2BI8SYdIrKcnPH4hmgOV9Y/VCTBI+WusDTAPREGfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
